elasticsearch:
  # es 服务地址
  host: 127.0.0.1
  # es 服务端口
  port: 9200

  # 配置日志级别,开启 debug 日志
logging:
  level:
    com.leo.service: debug
    org.springframework.data.elasticsearch.client.WIRE: trace
